### ISSUE TITLE
NuGet Support??

### ISSUE THREAD

**Issue by kinetiq** [snickler/EFCore-FluentStoredProcedure#11]
Am I correct that there is no nuget support for this?

If you want people to use this, you really need nuget. You could probably have it done in an hour, and far more people will be able to use this. 

Including me. I don't want to take any references that don't have nuget packages.

**Comment by snickler** [comment]
You make a good point. That's my fault. I'll get one up tonight ??.

Get Outlook for Android

________________________________

**Comment by snickler** [comment]
This is now resolved. Nuget package is available https://www.nuget.org/packages/Snickler.EFCore

**Comment by kinetiq** [comment]
That worked - thanks man! And by the way, thanks for the project. It fills a very annoying hole. :)
