### ISSUE TITLE
Update to EF Core 2.1

### ISSUE THREAD

**Issue by pantonis** [snickler/EFCore-FluentStoredProcedure#17]
Hi,

Can you update project to support EF Core 2.1?

Thanks

**Comment by snickler** [comment]
If you’re down for it, feel free to fork the repo and make a PR. That would be super helpful.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by snickler** [comment]
The Version 1.0.2 NuGet is out and fixes this.

**Comment by pantonis** [comment]
Thanks
