### ISSUE TITLE
New nuget?

### ISSUE THREAD

**Issue by rinkeb** [snickler/EFCore-FluentStoredProcedure#18]
Hi there,

Any chance for a new nuget, to get https://github.com/snickler/EFCore-FluentStoredProcedure/commit/820af34a0b833027f07f9ae0eb47dea6843464df on board?

**Comment by snickler** [comment]
Ah yes. I'll have that today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snickler** [comment]
Version 1.0.2 is now available.

**Comment by rinkeb** [comment]
Great, thanx!
