### ISSUE TITLE
Multiple result sets.

### ISSUE THREAD

**Issue by dazinator** [snickler/EFCore-FluentStoredProcedure#2]

**Comment by snickler** [comment]
@dazinator - Thanks for the contribution ^_^.

**Comment by dazinator** [comment]
You're welcome. Thanks for the blog post!

**Comment by snickler** [comment]
No problem. I just thought of something. Mind updating the README.MD with the updated syntax?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dazinator** [comment]
PR sent.
