### ISSUE TITLE
Rows Affected

### ISSUE THREAD

**Issue by kinetiq** [snickler/EFCore-FluentStoredProcedure#22]
First off, love this project, thanks for putting it out there. 

Here's my question: is there a way to get access to rows affected? 

I'm using this in a situation where the sproc is just doing some inserts, but no rows are returned. In this case, SQL Server returns the number of rows affected, but so far I don't see a way to get access to that. It seems like it would be a property on handler:

var result = 0;

db.LoadStoredProc("dbo.sproc_ImportUsers")
 .WithSqlParam("...", "...")
 ...
 .ExecuteStoredProc(handler => { result = handler.RowsAffected });

... Or, perhaps even better, just have ExecuteStoredProc return an int and have an overload that doesn't require the handler parameter:

return db.LoadStoredProc("...").ExecuteStoredProc(); 

Thanks!

**Comment by snickler** [comment]
Hmmm that's a good question. I'll see if I can figure out a way for this to be returned.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mooshpot** [comment]
I've proposed an update #23  which adds two new methods for non-query results i.e. just use SQL output parameters or nothing that also can return the number of rows affected.

You MUST make sure that SET NOCOUNT ON; is not in the stored procedure otherwise -1 will be returned! :)

**Comment by snickler** [comment]
Awesome, I'll take a look at this now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snickler** [comment]
#23 is merged into master. I'll get a NuGet package update out in an hour or so

**Comment by mooshpot** [comment]
Cheers mate! :)

**Comment by kinetiq** [comment]
Great, thanks guys!
