### ISSUE TITLE
Support EF Core 3.x

### ISSUE THREAD

**Issue by snickler** [snickler/EFCore-FluentStoredProcedure#30]

**Comment by berlstone** [comment]
While using with EF Core 3.0, I am getting the below error when calling a stored procedure with multiple result set

> Could not load type 'Microsoft.EntityFrameworkCore.RelationalMetadataExtensions' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by snickler** [comment]
Thanks for this. I'm going to look into this. Does this only blow up when it's a multiple result set?

**Comment by berlstone** [comment]
The error is because, the below method (line 31) is obsolete in EF Core 3.0

> context.Model.Relational().DefaultSchema

I have fixed the issue by replacing the code with 

> context.Model.GetDefaultSchema();

It is working fine!

**Comment by snickler** [comment]
Awesome! I'm going to update the packages to support the both. Thanks for finding this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snickler** [comment]
#31  fixes this.
