### ISSUE TITLE
System.TypeLoadException when trying to Load Stored Procedure with Output parameters and without Resultset

### ISSUE THREAD

**Issue by Chris-1995** [snickler/EFCore-FluentStoredProcedure#36]
My EFCore Version is v3.1.4 and my Snickler EFCore Version is v1.1.0.

I want to execute the following Code:      
...
   DbParameter outputParam1 = null;
   DbParameter outputParam2 = null;
...
context.LoadStoredProc("ProcedureName")
                .WithSqlParam("@ID", ID)
                .WithSqlParam("@param1", (dbParam) =>
               {
                   dbParam.Direction = ParameterDirection.Output;
                   dbParam.DbType = DbType.Int32;
                   outputParam1 = dbParam;
               })
                .WithSqlParam("@param2", (dbParam) =>
               {
                   dbParam.Direction = ParameterDirection.Output;
                   dbParam.DbType = DbType.Int32;
                   outputParam2 = dbParam;
               }).ExecuteStoredNonQuery();

And get this Error:
System.TypeLoadException: "The Type "Microsoft.EntityFrameworkCore.RelationalMetadataExtensions" in the Assembly "Microsoft.EntityFrameworkCore.Relational, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" could not be loaded."

Should I use Different Version of EFCore or Snickler Library to fix this issue?

**Comment by snickler** [comment]
I'm going to make a quick patch today for this. It's an error on my part since in EFCore 3.0, it explicitly targeted .NET Standard 2.1, but that was reversed in EFCore 3.1. The EASIEST way to make it work right now before patch is to retarget your library to .NET Standard 2.1. I think I have a good way to fix this for everyone, now. 

This issue is related to #34

**Comment by Chris-1995** [comment]
Thanks for the quick answer and the fix!

**Comment by Chris-1995** [comment]
Fix in branch "EFCore3" is not working for me. I cloned the Project and build it. After all I got the same error. Any Idea why?
![grafik](https://user-images.githubusercontent.com/12492551/83747744-5ec18200-a661-11ea-9e9b-9d5e3c8958bf.png)

**Comment by snickler** [comment]
Fix is coming in about 15-20 minutes. Sorry for the long wait, I happened to find the easiest way to pull this off and remove some hardcoded things.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by snickler** [comment]
@Chris-1995  - I created a 2.0 version of the Nuget Package. Please try that and see if it works out for you.

**Comment by Chris-1995** [comment]
Now it works!
The delay is no problem. It is a nice library and worth to wait for the changes.
Thanks :)
