### ISSUE TITLE
Critical problems moving to NET6

### ISSUE THREAD

**Issue by kinetiq** [snickler/EFCore-FluentStoredProcedure#40]
After migrating to NET6, this code results in:

     System.MissingMethodException: Method not found: 'System.Object Microsoft.EntityFrameworkCore.Infrastructure.IAnnotatable.get_Item(System.String)'. at Snickler.EFCore.EFExtensions.LoadStoredProc(DbContext context, String storedProcName, Boolean prependDefaultSchema, Int16 commandTimeout) at Keystone.Data.Sprocs.Sproc_ProgressStats(KeystoneDb db, Int32 projectSubjectId) in D:\Dev\Kinetiq\Keystone\Dev\Keystone.Data\Sprocs.cs:line 

Here's the code:

        public static List<AllProgressStatsDTO> Sproc_AllProgressStats(this KeystoneDb db, int userId)
        {
            IList<AllProgressStatsDTO> result = new List<AllProgressStatsDTO>();

            db.LoadStoredProc("dbo.sproc_AllProgressStats")
                .WithSqlParam("UserID", userId)
                .ExecuteStoredProc(handler =>
                {
                    result = handler.ReadToList<AllProgressStatsDTO>();
                });

            return result.ToList();
        }
        
Any thoughts? This is blocking my team today.

**Comment by kinetiq** [comment]
Found this discussion which is tangentially related (it is actually about EF 5): ttps://pretagteam.com/question/entity-framework-method-not-found-version-issue

This line caught my eye:

_Also this is a binary breaking change only, just recompiling would be enough to fix it._

Might be nothing, but it makes me wonder if it could be as simple as rebuilding.

**Comment by snickler** [comment]
Thanks for finding this. I'll work on getting a fix out. 

Do you happen to have the versions of the dependencies you're using?

**Comment by kinetiq** [comment]
@snickler  Thanks for getting back to me so fast. 

The entire solution is on NET6. 

I'm on EntityFrameworkCore, version 6.0.0 across the board:
 - Microsoft.EntityFramework.Core
 - Microsoft.EntityFramework.Design
 - Microsoft.EntityFramework.InMemory
 - Microsoft.EntityFramework.Relational
 - Microsoft.EntityFramework.SqlServer

As for Snickler, it's Snickler.EFCore 2.0.0

This is happening in an MVC project and also Azure Functions. 

Let me know if you need any more information from me or if I can help in any way!

**Comment by snickler** [comment]
@kinetiq - I'm working on a repro for this. I found that it's happening only with the NuGet package (likely due to how it's packaged). I'll get a new one up in a little bit!

**Comment by kinetiq** [comment]
@snickler Maybe that goes to the idea above, that it just needs to be rebuilt? In any case, thanks a lot, and I'm sure this will end up helping a lot of folks as they move up to NET6.

**Comment by snickler** [comment]
@kinetiq  - I'm 99.9999% sure it's an issue with it conditionally pulling in the SQLServer package for both netstandard 1.4 and netstandard 2.0. Something changes AS SOON as you switch the target to .NET 6 to make it blow up. .NET 5 works completely fine. I'm going to modify that and put out a new version after testing locally.

**Comment by snickler** [comment]
OH, this is why...

> EF Core 6.0 requires .NET 6. EF Core 6.0 does not target any .NET Standard version; for more information see the future of .NET Standard.

Yeah, fix incoming.

**Comment by kinetiq** [comment]
I was told versioning hell was over as of NET 6...  Was I lied to, Snickler?? :)

**Comment by snickler** [comment]
@kinetiq - I think this one was just a one-off EFCore decision, but still my fault in the end haha.

**Comment by snickler** [comment]
@kinetiq - I published a new version. It may still be validating, but when it's ready - update.

https://www.nuget.org/packages/Snickler.EFCore/3.0.0

**Comment by kinetiq** [comment]
Confirmed that this works on MVC! Thanks a lot, I am a fan for life.

**Comment by snickler** [comment]
Awesome! I'm happy to help. Thanks so much for bringing this to my attention \o/

**Comment by kinetiq** [comment]
You bet. Confirmed working in Azure Functions as well. Closing this, and thanks again!
