### ISSUE TITLE
Remap stored procedure output column names

### ISSUE THREAD

**Issue by chrish-slingshot** [snickler/EFCore-FluentStoredProcedure#42]
Is there a way to specify column names from the output? I.e. my SP returns column "aaa" but it maps to property "bbb" in my class. In similar frameworks I've seen this handled by tagging the property with an attribute like [StoredProcedure.Name("aaa")].

**Comment by snickler** [comment]
Currently, this library doesn't have that feature. Seems like a good one to add though!

**Comment by chrish-slingshot** [comment]
Created a PR with a possible fix for this.
