### ISSUE TITLE
Consider ditching Activator.CreateInstance

### ISSUE THREAD

**Issue by dazinator** [snickler/EFCore-FluentStoredProcedure#5]
You could ditch `Activator.CreateInstance` for a public default constructor constraint on type T. i.e:

```

            private IList<T> MapToList<T>(DbDataReader dr) where T: new()
            {
                var objList = new List<T>();
                var props = typeof(T).GetRuntimeProperties();

                var colMapping = dr.GetColumnSchema()
                    .Where(x => props.Any(y => y.Name.ToLower() == x.ColumnName.ToLower()))
                    .ToDictionary(key => key.ColumnName.ToLower());

                if (dr.HasRows)
                {
                    while (dr.Read())
                    {
                        T obj = new T();
                        foreach (var prop in props)
                        {
                            var val = dr.GetValue(colMapping[prop.Name.ToLower()].ColumnOrdinal.Value);
                            prop.SetValue(obj, val == DBNull.Value ? null : val);
                        }
                        objList.Add(obj);
                    }
                }
                return objList;
            }

```

You could also cache the `props` for type T, to save calling `GetRuntimeProperties` on every call you could grab them from the cache if they are there. Not sure how much that would save as I haven't checked to see if `GetRuntimeProperties` does caching of it's own.

**Comment by sp00ky** [comment]
Seems like a candidate for a pull request.

**Comment by snickler** [comment]
I was thinking of something in regards to this. I believe we should switch this to use an Expression Tree instead of reflection. We'll get some great speed improvements out of it. I can look into it over the next few days and see what I can whip up
