### ISSUE TITLE
Nuget package release?

### ISSUE THREAD

**Issue by dazinator** [snickler/EFCore-FluentStoredProcedure#6]
Consider releasing as a nuget package

**Comment by snickler** [comment]
Good idea. I'll get working on this sometime this week.

**Comment by rbhargaw2148** [comment]
Thanks for making our life easier! A very nice extension with or without nuget :)

**Comment by snickler** [comment]
This is now resolved. Nuget package is available https://www.nuget.org/packages/Snickler.EFCore
